version: '3.7'

services:
  haproxy:
    image: haproxy:alpine
    ports:
      - "5000:5000"
      - "5001:5001"
    secrets:
      - haproxy_cfg
    command:
      - haproxy
      - -f
      - /run/secrets/haproxy_cfg

  etcdnode1:
    image: quay.io/coreos/etcd:v3.5.5
    volumes:
      - etcd_data:/etcd_data
    entrypoint: etcd
    command:
      - -name
      - etcdnode1
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcdnode1:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcdnode1:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380
      - -initial-cluster
      - etcdnode1=http://etcdnode1:2380

  dbnode1:
    build: &build
      context: .
      args:
        - POSTGRES_VERSION=15.2
        - PATRONI_VERSION=2.1.7
    image: mazzolino/patroni:2.1.7-postgres15
    hostname: dbnode1
    volumes:
        - db-1-data:/data
        - ./config/wal-e:/etc/wal-e.d/env
    env_file:
      - .env
    environment:
      PATRONI_ETCD3_HOST: etcdnode1:2379
    deploy:
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - etcdnode1

  dbnode2:
    build: *build
    image: mazzolino/patroni:2.1.7-postgres15
    hostname: dbnode2
    volumes:
      - db-2-data:/data
      - ./config/wal-e:/etc/wal-e.d/env
    env_file:
      - .env
    environment:
      PATRONI_ETCD3_HOST: etcdnode1:2379
    deploy:
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - etcdnode1

  dbnode3:
    build: *build
    image: mazzolino/patroni:2.1.7-postgres15
    hostname: dbnode3
    volumes:
      - db-3-data:/data
      - ./config/wal-e:/etc/wal-e.d/env
    env_file:
      - .env
    environment:
      PATRONI_ETCD3_HOST: etcdnode1:2379
    deploy:
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - etcdnode1

  healthcheck:
    build:
      context: healthcheck
    image: mazzolino/patroni-healthcheck:2
    env_file: .env.healthcheck
    environment:
      - PATRONI_URL=http://haproxy:8008
      - SLEEP_TIME=30

volumes:
  db-1-data:
  db-2-data:
  db-3-data:
  etcd_data:

secrets:
   haproxy_cfg:
     file: config/haproxy.cfg
