#!/bin/bash
set -euo pipefail

export PATRONI_NAME="$HOSTNAME"
export PATRONI_POSTGRESQL_DATA_DIR="/data/$HOSTNAME"
export PATRONI_POSTGRESQL_CONNECT_ADDRESS="$HOSTNAME:5432"
export PATRONI_RESTAPI_CONNECT_ADDRESS="$HOSTNAME:8008"

exec patroni "$@"
